# Generated by Django 4.2.4 on 2023-11-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='town',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
