# Generated by Django 4.2.4 on 2023-11-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_age_user_gender_user_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
