# Generated by Django 4.2.4 on 2023-11-14 22:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyvacancy',
            old_name='email',
            new_name='username',
        ),
        migrations.AlterUniqueTogether(
            name='companyvacancy',
            unique_together={('name', 'username')},
        ),
    ]
