# Generated by Django 4.2.4 on 2023-11-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_companydocuments_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydocuments',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='company_files'),
        ),
    ]
