# Generated by Django 4.2.4 on 2023-11-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_companydocuments_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydocuments',
            old_name='files',
            new_name='file',
        ),
    ]
