# Generated by Django 4.2.4 on 2023-11-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_alter_companydocuments_doc_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydocuments',
            name='doc_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
