# Generated by Django 4.2.4 on 2023-11-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_companydocuments_doc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyvacancy',
            name='experience',
            field=models.BooleanField(default=None),
        ),
    ]
