# Generated by Django 4.2.4 on 2023-11-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_alter_companyvacancy_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyvacancy',
            name='open_vacancies',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
