# Generated by Django 4.2.4 on 2023-11-24 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_alter_companyvacancy_open_vacancies'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30)),
                ('answer', models.CharField(max_length=100)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companyvacancy')),
            ],
        ),
    ]
