# Generated by Django 4.2.4 on 2023-11-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_initialtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InitialTest',
        ),
    ]
