# Generated by Django 4.2.4 on 2023-11-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_delete_initialtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyvacancy',
            name='initial_test',
            field=models.CharField(blank=True, default='Теста нет', null=True),
        ),
        migrations.CreateModel(
            name='InitialTestAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companyvacancy')),
            ],
        ),
    ]
