# Generated by Django 4.2.4 on 2023-11-28 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0024_alter_initialtestanswers_answer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyvacancy',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='companyvacancy',
            name='username',
        ),
        migrations.CreateModel(
            name='UsersTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companyvacancy')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('test', 'username')},
            },
        ),
    ]
