# Generated by Django 4.2.4 on 2023-11-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_alter_companyvacancy_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstests',
            name='status',
            field=models.CharField(default='Не оценён', max_length=50),
        ),
    ]
